export const JobDataByCategory = {
  "Software-Engineers": [
    {
      id: 1,
      title: "Software Engineer",
      description: "Develop and maintain software applications.",
      salary: "$80,000 - $100,000",
      location: "San Francisco, CA",
      experienceRequired: "2-5 years",
      keyResponsibilities: "Write clean and efficient code...",
      education: "Bachelor's degree in Computer Science...",
      minimumQualifications: "Strong knowledge of JavaScript...",
      employmentType: "Full-time",
      mustSkills: "React, Node.js, SQL...",
    },
    {
      id: 2,
      title: "Frontend Developer",
      description: "Build user interfaces for web applications.",
      salary: "$70,000 - $90,000",
      location: "New York, NY",
      experienceRequired: "3-6 years",
      keyResponsibilities: "Implement UI designs...",
      education: "Bachelor's degree in Web Development...",
      minimumQualifications: "Proficiency in HTML, CSS, JavaScript...",
      employmentType: "Contract",
      mustSkills: "React, Redux, CSS Frameworks...",
    },
    {
      id: 3,
      title: "Backend Developer",
      description: "Develop server-side logic and APIs.",
      salary: "$75,000 - $95,000",
      location: "Seattle, WA",
      experienceRequired: "4-8 years",
      keyResponsibilities: "Build scalable backend systems...",
      education: "Bachelor's degree in Computer Science...",
      minimumQualifications: "Expertise in Node.js, Express...",
      employmentType: "Full-time",
      mustSkills: "Node.js, Express, MongoDB...",
    },
    {
      id: 4,
      title: "Full Stack Developer",
      description: "Work on both frontend and backend development.",
      salary: "$85,000 - $110,000",
      location: "Chicago, IL",
      experienceRequired: "3-7 years",
      keyResponsibilities: "Handle end-to-end development...",
      education: "Bachelor's degree in Software Engineering...",
      minimumQualifications: "Proficiency in HTML, CSS, JavaScript...",
      employmentType: "Permanent",
      mustSkills: "React, Node.js, Express, MongoDB...",
    },
  ],
  "Data-Scientists": [
    {
      id: 5,
      title: "Data Scientist",
      description: "Analyze and interpret data for insights.",
      salary: "$90,000 - $110,000",
      location: "New York, NY",
      experienceRequired: "3-7 years",
      keyResponsibilities: "Conduct data analysis...",
      education: "Master's degree in Data Science...",
      minimumQualifications: "Proficiency in Python...",
      employmentType: "Contract",
      mustSkills: "Machine Learning, Data Visualization...",
    },
    {
      id: 6,
      title: "Senior Data Scientist",
      description: "Lead data science projects and teams.",
      salary: "$110,000 - $130,000",
      location: "San Francisco, CA",
      experienceRequired: "6-10 years",
      keyResponsibilities: "Manage data science initiatives...",
      education: "PhD in Data Science or related field...",
      minimumQualifications: "Extensive experience in statistical modeling...",
      employmentType: "Full-time",
      mustSkills: "Python, R, Deep Learning...",
    },
    {
      id: 7,
      title: "Data Analyst",
      description: "Extract and analyze data for insights.",
      salary: "$60,000 - $80,000",
      location: "Chicago, IL",
      experienceRequired: "1-3 years",
      keyResponsibilities: "Prepare reports and visualizations...",
      education: "Bachelor's degree in Statistics or related field...",
      minimumQualifications: "Proficiency in SQL and Excel...",
      employmentType: "Permanent",
      mustSkills: "Data Analysis, SQL, Excel...",
    },
    {
      id: 8,
      title: "Machine Learning Engineer",
      description: "Develop and deploy ML models.",
      salary: "$100,000 - $120,000",
      location: "Seattle, WA",
      experienceRequired: "4-8 years",
      keyResponsibilities: "Build ML algorithms and pipelines...",
      education: "Master's degree in Computer Science...",
      minimumQualifications: "Strong programming skills in Python...",
      employmentType: "Full-time",
      mustSkills: "Machine Learning, TensorFlow, Python...",
    },
    {
      id: 9,
      title: "AI Research Scientist",
      description: "Conduct research on AI technologies.",
      salary: "$120,000 - $150,000",
      location: "Boston, MA",
      experienceRequired: "7+ years",
      keyResponsibilities: "Lead AI research projects...",
      education: "PhD in Artificial Intelligence or related field...",
      minimumQualifications: "Expertise in neural networks...",
      employmentType: "Full-time",
      mustSkills: "Deep Learning, NLP, Python...",
    },
  ],

  "Product-Managers": [
    {
      id: 10,
      title: "Product Manager",
      description: "Manage product development and strategy.",
      salary: "$90,000 - $120,000",
      location: "Seattle, WA",
      experienceRequired: "5+ years",
      keyResponsibilities: "Define product roadmap...",
      education: "Bachelor's degree in Business or related field...",
      minimumQualifications: "Proven experience in product management...",
      employmentType: "Permanent",
      mustSkills: "Product Strategy, Agile Methodology...",
    },
    {
      id: 11,
      title: "Senior Product Manager",
      description: "Lead product teams and roadmap.",
      salary: "$120,000 - $150,000",
      location: "San Francisco, CA",
      experienceRequired: "8+ years",
      keyResponsibilities: "Oversee product strategy and execution...",
      education: "Master's degree in Business Administration...",
      minimumQualifications: "Extensive leadership experience...",
      employmentType: "Full-time",
      mustSkills: "Product Development, Team Management...",
    },
    {
      id: 12,
      title: "Technical Product Manager",
      description: "Bridge the gap between technical and business teams.",
      salary: "$100,000 - $130,000",
      location: "New York, NY",
      experienceRequired: "6-10 years",
      keyResponsibilities: "Collaborate with engineering and design teams...",
      education: "Bachelor's degree in Engineering or related field...",
      minimumQualifications: "Strong technical background...",
      employmentType: "Permanent",
      mustSkills: "Agile Methodology, Software Development...",
    },
    {
      id: 13,
      title: "Product Marketing Manager",
      description: "Develop marketing strategies for product launches.",
      salary: "$80,000 - $100,000",
      location: "Chicago, IL",
      experienceRequired: "3-5 years",
      keyResponsibilities: "Create and execute marketing campaigns...",
      education: "Bachelor's degree in Marketing or related field...",
      minimumQualifications: "Experience in product marketing...",
      employmentType: "Full-time",
      mustSkills: "Marketing Strategy, Brand Management...",
    },
  ],
};
